### ISSUE TITLE
GPU Memory Increases

### ISSUE THREAD

**Issue by MBAnslow** [ywk991112/pytorch-chatbot#15]
Running this on a GPU makes the memory slowly increase leading to an out of memory error. Is there any way to fix this?

**Comment by sashank06** [comment]
1. Try to reduce the batch size
2. Try reducing the size of the vocabulary.

**Comment by MBAnslow** [comment]
I've solved the problem and it wasn't with your code. I didn't understand the way cuda caches/reserves memory in the gpu. In particular, unless you explicitly empty the memory cache, it reuses memory in the gpu. So if you use nvidia-smi it looks like a lot of memory is being used that isn't really. I was experimenting with larger sentence lengths and what was happening was that the reserved memory was increasing every now and again, corresponding to longer and longer sentences occurring in the batches whenever they occurred.  At some point this resulted in a out of memory error. It looked like the memory usage was gradually increasing but actually, it was finding larger and larger examples of batches until it led to the batch that raised an out of memory error.

**Comment by ywk991112** [comment]
Maybe you can try to decrease batch size whenever there is a long sentence in the batch while preprocessing.
